Repository Kavprabath/Green-Connect, pull requests merged in 2021-05, with the labels that each got.

#63 Renamed the file names and deleted the main.js fil
  Home/assets/js/main.js
  Login/index.html
  Login/login.html
  Signup/index.html
  Signup/signup.html
Labels: Changed

#64 Delete Login directory
  Login/assets/bootstrap/css/bootstrap.min.css
  Login/assets/bootstrap/js/bootstrap.min.js
  Login/assets/css/Login-Form-Clean.css
  Login/assets/css/styles.css
  Login/assets/img/Colors.png
  Login/assets/img/image (2).jpeg
  Login/assets/img/nsbm-full.jpg
  Login/assets/img/nsbm-full.png
  Login/assets/js/jquery.min.js
  Login/login.html
Labels: bug

#65 Login Page Updated
  Log In/assets/bootstrap/css/bootstrap.min.css
  Log In/assets/bootstrap/js/bootstrap.min.js
  Log In/assets/css/styles.css
  Log In/assets/img/email.svg
  Log In/assets/img/nsbm-full.jpg
  Log In/assets/img/passwor icon.svg
  Log In/assets/js/jquery.min.js
  Log In/login.html
Labels: Changed

#66 added js folder and index.js
  js/index.js
Labels: Changed, enhancement

#68 firebase initializing
  .vscode/settings.json
  Log In/assets/css/styles.css
  Log In/assets/js/jquery.min.js
  Log In/login.html
  js/firebase.js
  js/index.js
Labels: Changed

#69 Delete Signup directory
  Signup/README.html
  Signup/assets/bootstrap/css/bootstrap.min.css
  Signup/assets/bootstrap/js/bootstrap.min.js
  Signup/assets/css/Login-Form-Clean.css
  Signup/assets/css/styles.css
  Signup/assets/img/Colors.png
  Signup/assets/img/DJI_0064.png
  Signup/assets/js/jquery.min.js
  Signup/signup.html
Labels: bug

#71 Sign up page updated
  Sign Up/assets/bootstrap/css/bootstrap.min.css
  Sign Up/assets/bootstrap/js/bootstrap.min.js
  Sign Up/assets/css/styles.css
  Sign Up/assets/img/GConnect Logo.png
  Sign Up/assets/img/email.svg
  Sign Up/assets/img/nsbm wallpaper 2.jpg
  Sign Up/assets/img/nsbm-full.jpg
  Sign Up/assets/img/passwor icon.svg
  Sign Up/assets/js/jquery.min.js
  Sign Up/index.html
Labels: Changed

#72 Delete Log In directory
  Log In/assets/bootstrap/css/bootstrap.min.css
  Log In/assets/bootstrap/js/bootstrap.min.js
  Log In/assets/css/styles.css
  Log In/assets/img/email.svg
  Log In/assets/img/nsbm-full.jpg
  Log In/assets/img/passwor icon.svg
  Log In/login.html
Labels: Changed

#74 updated-login-page
  Log In/assets/bootstrap/css/bootstrap.min.css
  Log In/assets/bootstrap/js/bootstrap.min.js
  Log In/assets/css/GConnect-Heading.css
  Log In/assets/css/styles.css
  Log In/assets/img/GConnect Logo.png
  Log In/assets/img/email.svg
  Log In/assets/img/nsbm-full.jpg
  Log In/assets/img/passwor icon.svg
  Log In/assets/js/jquery.min.js
  Log In/login.html
Labels: Changed

#76 Firebase Initialize for the Sign Up Page
  Sign Up/signup.html
  js/firebase.js
Labels: Completed, bug

#79 signup page firebase conversation
  Sign Up/assets/bootstrap/css/bootstrap.min.css
  Sign Up/assets/bootstrap/js/bootstrap.min.js
  Sign Up/assets/css/styles.css
  Sign Up/assets/img/GConnect Logo.png
  Sign Up/assets/img/email.svg
  Sign Up/assets/img/nsbm wallpaper 2.jpg
  Sign Up/assets/img/nsbm-full.jpg
  Sign Up/assets/img/passwor icon.svg
  Sign Up/assets/js/jquery.min.js
  Sign Up/signup.html
  js/firebase.js
Labels: ASAP, Changed

#83 authorized the user login
  Log In/login.html
  Sign Up/signup.html
  js/firebase.js
Labels: ASAP

#85 added signout functions to the home page
  Home/home.html
  js/firebase.js
Labels: ASAP

#94 country removed
  views/userProfile.ejs
Labels: Changed

#95 user added
  node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node
  public/images/cover-1622283639607-MyEdit.jpg
  public/images/profile-1622283645263-IMG-20200217-WA0065-01.jpg
Labels: Added

#96 .
  views/userProfile.ejs
Labels: Changed
