Repository Kavprabath/Green-Connect, pull requests merged in 2021-03, with the labels that each got.

#4 Rename the profileview index page
  ProfileView/profileView.html
Labels: Changed, Fixed

#19 .
  ProfileView/profileView.html
Labels: Completed

#20 Basic Home Template With the Navigation
  Home/assets/css/normalize.css
  Home/assets/css/styles.css
  Home/assets/img/Green_Connect_Logo.png
  Home/assets/img/bell.png
  Home/assets/img/bookmark.svg
  Home/assets/img/chat bubble.png
  Home/assets/img/drop-down.png
  Home/assets/img/home.svg
  Home/assets/img/multiple-users-silhouette.svg
  Home/assets/img/university.svg
  Home/assets/img/user1.jpg
  Home/home.html
Labels: Completed, Still Bug

#21 image view
  ProfileView/assets/css/styles.css
  ProfileView/assets/js/script.min.js
  ProfileView/profileView.html
Labels: Changed

#24 image view changed
  ProfileView/assets/css/styles.css
  ProfileView/assets/js/script.min.js
  ProfileView/profileView.html
Labels: Changed

#27 nav bar added
  ProfileView/assets/css/styles.css
  ProfileView/assets/img/Green_Connect_Logo.png
  ProfileView/assets/img/bell.png
  ProfileView/assets/img/bookmark.svg
  ProfileView/assets/img/chat bubble.png
  ProfileView/assets/img/drop-down.png
  ProfileView/assets/img/home.svg
  ProfileView/assets/img/multiple-users-silhouette.svg
  ProfileView/assets/img/university.svg
  ProfileView/assets/img/user1.jpg
  ProfileView/profileView.html
Labels: Completed

#28 Devinda007
  ProfileEdit/assets/css/Contact-Form-Clean.css
  ProfileEdit/assets/css/styles.css
  ProfileEdit/assets/css/untitled.css
  ProfileEdit/assets/img/avatar.webp
  ProfileEdit/assets/img/camera1.png
  ProfileEdit/assets/img/camera2.png
  ProfileEdit/assets/img/pngegg.png
  ProfileEdit/index.html
Labels: Completed

#30 added right follow card section #11
  Home/assets/css/styles.css
  Home/home.html
Labels: Completed

#32 added upcoming event section
  Home/assets/css/styles.css
  Home/home.html
Labels: Completed, enhancement

#34 changed event names and correct the layout
  Home/assets/css/styles.css
  Home/home.html
Labels: Changed, Completed

#36 side components are now fixed
  Home/assets/css/styles.css
Labels: Fixed

#38 navbar position fixed
  Home/assets/css/styles.css
Labels: Fixed

#39 main status template added
  Home/assets/css/styles.css
  Home/home.html
Labels: enhancement

#41 text input area added to main status section
  Home/assets/css/styles.css
  Home/assets/img/gym.svg
  Home/assets/img/happy.svg
  Home/assets/img/image.svg
  Home/home.html
Labels: Changed

#42 completed main status section
  Home/assets/css/styles.css
  Home/assets/img/gym.svg
  Home/assets/img/happy.svg
  Home/assets/img/image.svg
  Home/home.html
Labels: Completed, enhancement

#43 user post section initialized
  Home/assets/css/styles.css
  Home/assets/img/NSBM-Green-University.jpg
  Home/assets/img/more.svg
  Home/home.html
Labels: Changed
